# Generated by Django 3.2.9 on 2021-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=False)),
                ('stu', models.BooleanField(default=False)),
                ('roll', models.BooleanField(default=False)),
            ],
        ),
    ]
